### ISSUE TITLE
how can I check https://wordpress.com/

### ISSUE THREAD

**Issue by vikramvi** [janexner/site-infrastructure-tests#5]
Hi,

Can you please share sample  project if I want to test a website say https://wordpress.com/

what are the different things I should check ?

As per https://support.google.com/analytics/answer/1032399?hl=en, I found this website has got /analytics.j

Thanks in advance.

**Comment by janexner** [comment]
Hi Vikram,

wordpress.com might not be the best example, they do not track a lot of things, to be honest.

![image](https://user-images.githubusercontent.com/9006232/32693452-60cc18f2-c72b-11e7-9318-169f4e55f576.png)

So the only data I can see in there is the language and charset. Maybe the list of IDs further down the URL parameters are also important, I don't know.

![image](https://user-images.githubusercontent.com/9006232/32693470-95dc8892-c72b-11e7-88d0-e6405fc35c93.png)

What the web analytics folk would love is for those data points "to be stable", so to speak. IF they track those now, they'd want to still track them after any site updates. That means a test frame work would have to check for those values somewhere.

We need to know where they come from, then. 
It is very likely that the "de" parameter ("utf-8") is read straight from the HTML &lt;meta charset="UTF-8"&gt; tag. So I would run regression test on that parameter, make sure it is always present.
Where the "ul" parameter comes from ("en-us") I do not know. It is not in the page anywhere. So they probably calculate that in Javascript somewhere. It might be possible to test the underlying data, e.g. the "lang" attribute on the &lt;html&gt; tag.
Same goes for the IDs in the second screenshots, I can't find them anywhere.

For a project that you'd work on, you would get input from analytics ("this is what data we really need") and dev ("this is how we surface it in the pages"), then build your test to check that data.

Simple example: on a product page on an ecommerce site, I would likely want to track product ID, price, maybe availability. I would ask my dev team to surface those data points. They might end up in a data layer, or just spread out across the DOM. THOSE data points, whereever they are, should be tested, to make sure they're still there after any major or minor release of the site.

Does that make any sense?

**Comment by vikramvi** [comment]
@janexner Thanks a zillion for detailed info and action points.

- To achieve the tasks you mentioned in above comment; I need to use appropraite apis exposed by **[HtmlUnit](http://htmlunit.sourceforge.net/)** right ?
- Goto particular page, get its pagesource > extract elements > compare against expected values ?
- Some people suggested using **[jsou](https://jsoup.org/)** . 

Can you please share merits / demerits of HtmlUnit approach vs jsoup approach ?
Thanks in advance.

**Comment by janexner** [comment]
Hi Vikram,

I wrote myself Java code which injects Javascript into the pages that checks things, yes.

Haven't worked with jsoup at all, tbh. Do you think it would have advantages?

**Comment by vikramvi** [comment]
> I wrote myself Java code which injects Javascript into the pages that checks things, yes.

- can you please point me to file which is doing this action in your project ?
- my understanding was one needs to use apis exposed by HtmlUnit

> Haven't worked with jsoup at all, tbh. Do you think it would have advantages?

- I'm not sure on this, as my expereicnes is with UI, API automation and this is first time I'm trying to do web analytics automation :)

**Comment by janexner** [comment]
Hi Vikram,

Take https://github.com/janexner/site-infrastructure-tests/blob/master/src/test/java/com/exner/tools/analyticstdd/SiteInfrastructureTests/tests/others/GTMLoadedTestCase.java as an example.

This is a test that checks whether a site has Google Tag Manager embedded or not. Line 18 is the crucial bit.

From the perspective of JUnit, the Java class is a test, and it passes or fails, based on that Javascript in line 18.

Does that make sense?

**Comment by vikramvi** [comment]
@janexner  Thanks again for clarification
